stages:
  - deploy

pages:
  stage: deploy
  image: ghcr.io/astral-sh/uv:python3.12-bookworm

  script:
    - uv sync --directory "docs"
    - uv run --directory "docs" mkdocs build --site-dir "../public"

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
